(define-module (octorine guix rust-crates)
  #:use-module (guix import crate)
  #:use-module (guix build-system cargo)
  #:use-module (octorine guix rust-sources)
  #:export (lookup-cargo-inputs)
  )


(define-cargo-inputs lookup-cargo-inputs
                     (aoc-cli =>
                              (list aoc-client-0.2.0
                                    rust-addr2line-0.21.0
                                    rust-adler-1.0.2
                                    rust-aho-corasick-1.1.2
                                    rust-android-tzdata-0.1.1
                                    rust-android-system-properties-0.1.5
                                    rust-anstream-0.6.4
                                    rust-anstyle-1.0.4
                                    rust-anstyle-parse-0.2.2
                                    rust-anstyle-query-1.0.0
                                    rust-anstyle-wincon-3.0.1
                                    rust-autocfg-1.1.0
                                    rust-backtrace-0.3.69
                                    rust-base64-0.21.5
                                    rust-bitflags-1.3.2
                                    rust-bitflags-2.4.1
                                    rust-bumpalo-3.14.0
                                    rust-bytes-1.5.0
                                    rust-cc-1.0.83
                                    rust-cesu8-1.1.0
                                    rust-cfg-if-1.0.0
                                    rust-chrono-0.4.31
                                    rust-clap-4.4.8
                                    rust-clap-builder-4.4.8
                                    rust-clap-derive-4.4.7
                                    rust-clap-lex-0.6.0
                                    rust-colorchoice-1.0.0
                                    rust-colored-2.0.4
                                    rust-combine-4.6.6
                                    rust-core-foundation-0.9.3
                                    rust-core-foundation-sys-0.8.4
                                    rust-dirs-4.0.0
                                    rust-dirs-sys-0.3.7
                                    rust-encoding-rs-0.8.33
                                    rust-env-logger-0.10.1
                                    rust-equivalent-1.0.1
                                    rust-errno-0.3.7
                                    rust-exit-code-1.0.0
                                    rust-fastrand-2.0.1
                                    rust-fnv-1.0.7
                                    rust-foreign-types-0.3.2
                                    rust-foreign-types-shared-0.1.1
                                    rust-form-urlencoded-1.2.0
                                    rust-futf-0.1.5
                                    rust-futures-channel-0.3.29
                                    rust-futures-core-0.3.29
                                    rust-futures-io-0.3.29
                                    rust-futures-sink-0.3.29
                                    rust-futures-task-0.3.29
                                    rust-futures-util-0.3.29
                                    rust-getrandom-0.2.11
                                    rust-gimli-0.28.0
                                    rust-h2-0.3.22
                                    rust-hashbrown-0.14.2
                                    rust-heck-0.4.1
                                    rust-hermit-abi-0.3.3
                                    rust-html2md-0.2.14
                                    rust-html2text-0.4.5
                                    rust-html5ever-0.26.0
                                    rust-http-0.2.11
                                    rust-http-body-0.4.5
                                    rust-httparse-1.8.0
                                    rust-httpdate-1.0.3
                                    rust-humantime-2.1.0
                                    rust-hyper-0.14.27
                                    rust-hyper-tls-0.5.0
                                    rust-iana-time-zone-0.1.58
                                    rust-iana-time-zone-haiku-0.1.2
                                    rust-idna-0.4.0
                                    rust-indexmap-2.1.0
                                    rust-ipnet-2.9.0
                                    rust-is-terminal-0.4.9
                                    rust-itoa-1.0.9
                                    rust-jni-0.19.0
                                    rust-jni-sys-0.3.0
                                    rust-js-sys-0.3.65
                                    rust-lazy-static-1.4.0
                                    rust-libc-0.2.150
                                    rust-libredox-0.0.1
                                    rust-linux-raw-sys-0.4.11
                                    rust-lock-api-0.4.11
                                    rust-log-0.4.20
                                    rust-mac-0.1.1
                                    rust-markup5ever-0.11.0
                                    rust-markup5ever-rcdom-0.2.0
                                    rust-memchr-2.6.4
                                    rust-mime-0.3.17
                                    rust-miniz-oxide-0.7.1
                                    rust-mio-0.8.9
                                    rust-native-tls-0.2.11
                                    rust-new-debug-unreachable-1.0.4
                                    rust-num-traits-0.2.17
                                    rust-num-cpus-1.16.0
                                    rust-object-0.32.1
                                    rust-once-cell-1.18.0
                                    rust-openssl-0.10.59
                                    rust-openssl-macros-0.1.1
                                    rust-openssl-probe-0.1.5
                                    rust-openssl-src-300.1.6+3.1.4
                                    rust-openssl-sys-0.9.95
                                    rust-parking-lot-0.12.1
                                    rust-parking-lot-core-0.9.9
                                    rust-percent-encoding-2.3.0
                                    rust-phf-0.10.1
                                    rust-phf-codegen-0.10.0
                                    rust-phf-generator-0.10.0
                                    rust-phf-shared-0.10.0
                                    rust-pin-project-lite-0.2.13
                                    rust-pin-utils-0.1.0
                                    rust-pkg-config-0.3.27
                                    rust-ppv-lite86-0.2.17
                                    rust-precomputed-hash-0.1.1
                                    rust-proc-macro2-1.0.69
                                    rust-quote-1.0.33
                                    rust-rand-0.8.5
                                    rust-rand-chacha-0.3.1
                                    rust-rand-core-0.6.4
                                    rust-redox-syscall-0.4.1
                                    rust-redox-users-0.4.4
                                    rust-regex-1.10.2
                                    rust-regex-automata-0.4.3
                                    rust-regex-syntax-0.8.2
                                    rust-reqwest-0.11.22
                                    rust-rustc-demangle-0.1.23
                                    rust-rustix-0.38.25
                                    rust-ryu-1.0.15
                                    rust-same-file-1.0.6
                                    rust-schannel-0.1.22
                                    rust-scopeguard-1.2.0
                                    rust-security-framework-2.9.2
                                    rust-security-framework-sys-2.9.1
                                    rust-serde-1.0.193
                                    rust-serde-derive-1.0.193
                                    rust-serde-json-1.0.108
                                    rust-serde-urlencoded-0.7.1
                                    rust-siphasher-0.3.11
                                    rust-slab-0.4.9
                                    rust-smallvec-1.11.2
                                    rust-socket2-0.4.10
                                    rust-socket2-0.5.5
                                    rust-string-cache-0.8.7
                                    rust-string-cache-codegen-0.5.2
                                    rust-strsim-0.10.0
                                    rust-syn-1.0.109
                                    rust-syn-2.0.39
                                    rust-system-configuration-0.5.1
                                    rust-system-configuration-sys-0.5.0
                                    rust-tempfile-3.8.1
                                    rust-tendril-0.4.3
                                    rust-term-size-0.3.2
                                    rust-termcolor-1.4.0
                                    rust-thiserror-1.0.50
                                    rust-thiserror-impl-1.0.50
                                    rust-tinyvec-1.6.0
                                    rust-tinyvec-macros-0.1.1
                                    rust-tokio-1.34.0
                                    rust-tokio-native-tls-0.3.1
                                    rust-tokio-util-0.7.10
                                    rust-tower-service-0.3.2
                                    rust-tracing-0.1.40
                                    rust-tracing-core-0.1.32
                                    rust-try-lock-0.2.4
                                    rust-unicode-bidi-0.3.13
                                    rust-unicode-ident-1.0.12
                                    rust-unicode-normalization-0.1.22
                                    rust-unicode-width-0.1.11
                                    rust-url-2.4.1
                                    rust-utf-8-0.7.6
                                    rust-utf8parse-0.2.1
                                    rust-vcpkg-0.2.15
                                    rust-walkdir-2.4.0
                                    rust-want-0.3.1
                                    rust-wasi-0.11.0+wasi-snapshot-preview1
                                    rust-wasm-bindgen-0.2.88
                                    rust-wasm-bindgen-backend-0.2.88
                                    rust-wasm-bindgen-futures-0.4.38
                                    rust-wasm-bindgen-macro-0.2.88
                                    rust-wasm-bindgen-macro-support-0.2.88
                                    rust-wasm-bindgen-shared-0.2.88
                                    rust-web-sys-0.3.65
                                    rust-winapi-0.3.9
                                    rust-winapi-i686-pc-windows-gnu-0.4.0
                                    rust-winapi-util-0.1.6
                                    rust-winapi-x86-64-pc-windows-gnu-0.4.0
                                    rust-windows-core-0.51.1
                                    rust-windows-sys-0.48.0
                                    rust-windows-targets-0.48.5
                                    rust-windows-aarch64-gnullvm-0.48.5
                                    rust-windows-aarch64-msvc-0.48.5
                                    rust-windows-i686-gnu-0.48.5
                                    rust-windows-i686-msvc-0.48.5
                                    rust-windows-x86-64-gnu-0.48.5
                                    rust-windows-x86-64-gnullvm-0.48.5
                                    rust-windows-x86-64-msvc-0.48.5
                                    rust-winreg-0.50.0
                                    rust-xml5ever-0.17.0))
                     (aoc-client =>
                                 (list rust-addr2line-0.24.2
                                  rust-adler2-2.0.1
                                  rust-aho-corasick-1.1.3
                                  rust-android-tzdata-0.1.1
                                  rust-android-system-properties-0.1.5
                                  rust-autocfg-1.5.0
                                  rust-backtrace-0.3.75
                                  rust-base64-0.21.7
                                  rust-bitflags-1.3.2
                                  rust-bitflags-2.9.3
                                  rust-bumpalo-3.19.0
                                  rust-bytes-1.10.1
                                  rust-cc-1.2.34
                                  rust-cesu8-1.1.0
                                  rust-cfg-if-1.0.3
                                  rust-chrono-0.4.41
                                  rust-colored-2.2.0
                                  rust-combine-4.6.7
                                  rust-core-foundation-0.9.4
                                  rust-core-foundation-sys-0.8.7
                                  rust-dirs-4.0.0
                                  rust-dirs-sys-0.3.7
                                  rust-displaydoc-0.2.5
                                  rust-encoding-rs-0.8.35
                                  rust-equivalent-1.0.2
                                  rust-errno-0.3.13
                                  rust-fastrand-2.3.0
                                  rust-fnv-1.0.7
                                  rust-foreign-types-0.3.2
                                  rust-foreign-types-shared-0.1.1
                                  rust-form-urlencoded-1.2.2
                                  rust-futf-0.1.5
                                  rust-futures-channel-0.3.31
                                  rust-futures-core-0.3.31
                                  rust-futures-io-0.3.31
                                  rust-futures-sink-0.3.31
                                  rust-futures-task-0.3.31
                                  rust-futures-util-0.3.31
                                  rust-getrandom-0.2.16
                                  rust-getrandom-0.3.3
                                  rust-gimli-0.31.1
                                  rust-h2-0.3.27
                                  rust-hashbrown-0.15.5
                                  rust-html2md-0.2.15
                                  rust-html2text-0.4.5
                                  rust-html5ever-0.26.0
                                  rust-html5ever-0.27.0
                                  rust-http-0.2.12
                                  rust-http-body-0.4.6
                                  rust-httparse-1.10.1
                                  rust-httpdate-1.0.3
                                  rust-hyper-0.14.32
                                  rust-hyper-tls-0.5.0
                                  rust-iana-time-zone-0.1.63
                                  rust-iana-time-zone-haiku-0.1.2
                                  rust-icu-collections-2.0.0
                                  rust-icu-locale-core-2.0.0
                                  rust-icu-normalizer-2.0.0
                                  rust-icu-normalizer-data-2.0.0
                                  rust-icu-properties-2.0.1
                                  rust-icu-properties-data-2.0.1
                                  rust-icu-provider-2.0.0
                                  rust-idna-1.1.0
                                  rust-idna-adapter-1.2.1
                                  rust-indexmap-2.11.0
                                  rust-io-uring-0.7.10
                                  rust-ipnet-2.11.0
                                  rust-itoa-1.0.15
                                  rust-jni-0.19.0
                                  rust-jni-sys-0.3.0
                                  rust-js-sys-0.3.77
                                  rust-lazy-static-1.5.0
                                  rust-libc-0.2.175
                                  rust-libredox-0.1.9
                                  rust-linux-raw-sys-0.9.4
                                  rust-litemap-0.8.0
                                  rust-lock-api-0.4.13
                                  rust-log-0.4.27
                                  rust-mac-0.1.1
                                  rust-markup5ever-0.11.0
                                  rust-markup5ever-0.12.1
                                  rust-markup5ever-rcdom-0.3.0
                                  rust-memchr-2.7.5
                                  rust-mime-0.3.17
                                  rust-miniz-oxide-0.8.9
                                  rust-mio-1.0.4
                                  rust-native-tls-0.2.14
                                  rust-new-debug-unreachable-1.0.6
                                  rust-num-traits-0.2.19
                                  rust-object-0.36.7
                                  rust-once-cell-1.21.3
                                  rust-openssl-0.10.73
                                  rust-openssl-macros-0.1.1
                                  rust-openssl-probe-0.1.6
                                  rust-openssl-sys-0.9.109
                                  rust-parking-lot-0.12.4
                                  rust-parking-lot-core-0.9.11
                                  rust-percent-encoding-2.3.2
                                  rust-phf-0.10.1
                                  rust-phf-0.11.3
                                  rust-phf-codegen-0.10.0
                                  rust-phf-codegen-0.11.3
                                  rust-phf-generator-0.10.0
                                  rust-phf-generator-0.11.3
                                  rust-phf-shared-0.10.0
                                  rust-phf-shared-0.11.3
                                  rust-pin-project-lite-0.2.16
                                  rust-pin-utils-0.1.0
                                  rust-pkg-config-0.3.32
                                  rust-potential-utf-0.1.3
                                  rust-ppv-lite86-0.2.21
                                  rust-precomputed-hash-0.1.1
                                  rust-proc-macro2-1.0.101
                                  rust-quote-1.0.40
                                  rust-r-efi-5.3.0
                                  rust-rand-0.8.5
                                  rust-rand-chacha-0.3.1
                                  rust-rand-core-0.6.4
                                  rust-redox-syscall-0.5.17
                                  rust-redox-users-0.4.6
                                  rust-regex-1.11.2
                                  rust-regex-automata-0.4.10
                                  rust-regex-syntax-0.8.6
                                  rust-reqwest-0.11.27
                                  rust-rustc-demangle-0.1.26
                                  rust-rustix-1.0.8
                                  rust-rustls-pemfile-1.0.4
                                  rust-rustversion-1.0.22
                                  rust-ryu-1.0.20
                                  rust-same-file-1.0.6
                                  rust-schannel-0.1.27
                                  rust-scopeguard-1.2.0
                                  rust-security-framework-2.11.1
                                  rust-security-framework-sys-2.14.0
                                  rust-serde-1.0.219
                                  rust-serde-derive-1.0.219
                                  rust-serde-json-1.0.143
                                  rust-serde-urlencoded-0.7.1
                                  rust-shlex-1.3.0
                                  rust-siphasher-0.3.11
                                  rust-siphasher-1.0.1
                                  rust-slab-0.4.11
                                  rust-smallvec-1.15.1
                                  rust-socket2-0.5.10
                                  rust-socket2-0.6.0
                                  rust-stable-deref-trait-1.2.0
                                  rust-string-cache-0.8.9
                                  rust-string-cache-codegen-0.5.4
                                  rust-syn-1.0.109
                                  rust-syn-2.0.106
                                  rust-sync-wrapper-0.1.2
                                  rust-synstructure-0.13.2
                                  rust-system-configuration-0.5.1
                                  rust-system-configuration-sys-0.5.0
                                  rust-tempfile-3.21.0
                                  rust-tendril-0.4.3
                                  rust-term-size-0.3.2
                                  rust-thiserror-1.0.69
                                  rust-thiserror-impl-1.0.69
                                  rust-tinystr-0.8.1
                                  rust-tokio-1.47.1
                                  rust-tokio-native-tls-0.3.1
                                  rust-tokio-util-0.7.16
                                  rust-tower-service-0.3.3
                                  rust-tracing-0.1.41
                                  rust-tracing-core-0.1.34
                                  rust-try-lock-0.2.5
                                  rust-unicode-ident-1.0.18
                                  rust-unicode-width-0.1.14
                                  rust-url-2.5.7
                                  rust-utf-8-0.7.6
                                  rust-utf8-iter-1.0.4
                                  rust-vcpkg-0.2.15
                                  rust-walkdir-2.5.0
                                  rust-want-0.3.1
                                  rust-wasi-0.11.1+wasi-snapshot-preview1
                                  rust-wasi-0.14.3+wasi-0.2.4
                                  rust-wasm-bindgen-0.2.100
                                  rust-wasm-bindgen-backend-0.2.100
                                  rust-wasm-bindgen-futures-0.4.50
                                  rust-wasm-bindgen-macro-0.2.100
                                  rust-wasm-bindgen-macro-support-0.2.100
                                  rust-wasm-bindgen-shared-0.2.100
                                  rust-web-sys-0.3.77
                                  rust-winapi-0.3.9
                                  rust-winapi-i686-pc-windows-gnu-0.4.0
                                  rust-winapi-util-0.1.10
                                  rust-winapi-x86-64-pc-windows-gnu-0.4.0
                                  rust-windows-core-0.61.2
                                  rust-windows-implement-0.60.0
                                  rust-windows-interface-0.59.1
                                  rust-windows-link-0.1.3
                                  rust-windows-result-0.3.4
                                  rust-windows-strings-0.4.2
                                  rust-windows-sys-0.48.0
                                  rust-windows-sys-0.52.0
                                  rust-windows-sys-0.59.0
                                  rust-windows-sys-0.60.2
                                  rust-windows-targets-0.48.5
                                  rust-windows-targets-0.52.6
                                  rust-windows-targets-0.53.3
                                  rust-windows-aarch64-gnullvm-0.48.5
                                  rust-windows-aarch64-gnullvm-0.52.6
                                  rust-windows-aarch64-gnullvm-0.53.0
                                  rust-windows-aarch64-msvc-0.48.5
                                  rust-windows-aarch64-msvc-0.52.6
                                  rust-windows-aarch64-msvc-0.53.0
                                  rust-windows-i686-gnu-0.48.5
                                  rust-windows-i686-gnu-0.52.6
                                  rust-windows-i686-gnu-0.53.0
                                  rust-windows-i686-gnullvm-0.52.6
                                  rust-windows-i686-gnullvm-0.53.0
                                  rust-windows-i686-msvc-0.48.5
                                  rust-windows-i686-msvc-0.52.6
                                  rust-windows-i686-msvc-0.53.0
                                  rust-windows-x86-64-gnu-0.48.5
                                  rust-windows-x86-64-gnu-0.52.6
                                  rust-windows-x86-64-gnu-0.53.0
                                  rust-windows-x86-64-gnullvm-0.48.5
                                  rust-windows-x86-64-gnullvm-0.52.6
                                  rust-windows-x86-64-gnullvm-0.53.0
                                  rust-windows-x86-64-msvc-0.48.5
                                  rust-windows-x86-64-msvc-0.52.6
                                  rust-windows-x86-64-msvc-0.53.0
                                  rust-winreg-0.50.0
                                  rust-wit-bindgen-0.45.0
                                  rust-writeable-0.6.1
                                  rust-xml5ever-0.17.0
                                  rust-xml5ever-0.18.1
                                  rust-yoke-0.8.0
                                  rust-yoke-derive-0.8.0
                                  rust-zerocopy-0.8.26
                                  rust-zerocopy-derive-0.8.26
                                  rust-zerofrom-0.1.6
                                  rust-zerofrom-derive-0.1.6
                                  rust-zerotrie-0.2.2
                                  rust-zerovec-0.11.4
                                  rust-zerovec-derive-0.11.1))
                     (lets-countdown =>
                                     (list rust-aho-corasick-1.1.3
                                      rust-anes-0.1.6
                                      rust-anstyle-1.0.7
                                      rust-autocfg-1.0.0
                                      rust-bumpalo-3.2.1
                                      rust-cast-0.3.0
                                      rust-cfg-if-0.1.10
                                      rust-cfg-if-1.0.0
                                      rust-ciborium-0.2.2
                                      rust-ciborium-io-0.2.2
                                      rust-ciborium-ll-0.2.2
                                      rust-clap-4.5.4
                                      rust-clap-builder-4.5.2
                                      rust-clap-lex-0.7.0
                                      rust-criterion-0.5.1
                                      rust-criterion-plot-0.5.0
                                      rust-crossbeam-deque-0.7.3
                                      rust-crossbeam-epoch-0.8.2
                                      rust-crossbeam-queue-0.2.1
                                      rust-crossbeam-utils-0.7.2
                                      rust-crunchy-0.2.2
                                      rust-either-1.5.3
                                      rust-half-2.4.1
                                      rust-hermit-abi-0.1.8
                                      rust-hermit-abi-0.3.9
                                      rust-is-terminal-0.4.12
                                      rust-itertools-0.10.5
                                      rust-itoa-0.4.5
                                      rust-js-sys-0.3.69
                                      rust-lazy-static-1.4.0
                                      rust-libc-0.2.68
                                      rust-log-0.4.8
                                      rust-maybe-uninit-2.0.0
                                      rust-memchr-2.7.2
                                      rust-memoffset-0.5.4
                                      rust-num-traits-0.2.19
                                      rust-num-cpus-1.12.0
                                      rust-once-cell-1.19.0
                                      rust-oorandom-11.1.0
                                      rust-plotters-0.3.5
                                      rust-plotters-backend-0.3.5
                                      rust-plotters-svg-0.3.5
                                      rust-proc-macro2-1.0.82
                                      rust-quote-1.0.36
                                      rust-rayon-1.3.0
                                      rust-rayon-core-1.7.0
                                      rust-regex-1.10.4
                                      rust-regex-automata-0.4.6
                                      rust-regex-syntax-0.8.3
                                      rust-ryu-1.0.3
                                      rust-same-file-1.0.6
                                      rust-scopeguard-1.1.0
                                      rust-serde-1.0.105
                                      rust-serde-derive-1.0.105
                                      rust-serde-json-1.0.49
                                      rust-syn-1.0.17
                                      rust-syn-2.0.63
                                      rust-tinytemplate-1.2.1
                                      rust-unicode-ident-1.0.12
                                      rust-unicode-xid-0.2.0
                                      rust-walkdir-2.3.1
                                      rust-wasm-bindgen-0.2.92
                                      rust-wasm-bindgen-backend-0.2.92
                                      rust-wasm-bindgen-macro-0.2.92
                                      rust-wasm-bindgen-macro-support-0.2.92
                                      rust-wasm-bindgen-shared-0.2.92
                                      rust-web-sys-0.3.69
                                      rust-winapi-0.3.8
                                      rust-winapi-i686-pc-windows-gnu-0.4.0
                                      rust-winapi-util-0.1.3
                                      rust-winapi-x86-64-pc-windows-gnu-0.4.0
                                      rust-windows-sys-0.52.0
                                      rust-windows-targets-0.52.5
                                      rust-windows-aarch64-gnullvm-0.52.5
                                      rust-windows-aarch64-msvc-0.52.5
                                      rust-windows-i686-gnu-0.52.5
                                      rust-windows-i686-gnullvm-0.52.5
                                      rust-windows-i686-msvc-0.52.5
                                      rust-windows-x86-64-gnu-0.52.5
                                      rust-windows-x86-64-gnullvm-0.52.5
                                      rust-windows-x86-64-msvc-0.52.5)))

